model_config_path = "ai-model/checkpoint/ckpt-10000/config.json"
model_path = "ai-model/checkpoint/ckpt-10000/pytorch_model.bin"
#model_config_path = 'ai-model/search_model/config.json'
#model_path = 'ai-model/search_model/model.10.bin'
tokenizer_path = "ai-model/search_model/vocab.txt"
trie_path = "ai-model/trie_data/kg_11_17.pkl"

cuda = "cpu"
pos_tag = {'n': '▂',
           'mq': '▃',
           'ul': '▅',
           'vg': '▇',
           't': '█',
           's': '▉',
           'm': '▋',
           'g': '▌',
           'y': '▍',
           'a': '▎',
           'p': '■',
           'z': '□',
           'tg': '▪',
           'rg': '▫',
           'r': '▬',
           'yg': '▲',
           'f': '△',
           'u': '▶',
           'x': '►',
           'v': '▼',
           'nrt': '▽',
           'c': '◆',
           'ad': '◇',
           'eng': '○',
           'ug': '◎',
           'uv': '●',
           'b': '◕',
           'an': '◠',
           'nr': '◢',
           'vn': '◤',
           'uz': '☀',
           'ud': '★',
           'vq': '☆',
           'mg': '☕',
           'uj': '☞',
           'ag': '☺',
           'h': '☼',
           'l': '♀',
           'zg': '♂',
           'nrfg': '♠',
           'd': '♡',
           'df': '♣',
           'o': '♥',
           'vd': '♦',
           'i': '♪',
           'nz': '♫',
           'e': '♬',
           'ns': '✈',
           'q': '✔',
           'ng': '✕',
           'k': '✖',
           'j': '✦',
           'nt': '✨'}

